void _puts_recursion(char *s);
int _putchar(char c);
void rev_printer(char *s, int n);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int counter(int count, char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int halp(int c, int i);
